config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  resources :product, only: [:show]
  resources :category, only: [:show]
  resource :cart, only: %i[destroy show] do
    resources :cart_items, only: %i[destroy create]
  end  
  resources :search, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profile,  only: [:index]
      resources :products, only: [:index]
    end  
  end  

  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  
  
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user

  validates :user_id, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :cart_id, :quantity, presence: true 
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true

  belongs_to :category
  has_many :galleries
  has_many :related_products
  has_many :related, through: :related_products

  enum hit: { hit: 1, not_hit: 0 }
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :related, class_name: 'Product'
end

app/models/user.rb
class User < ApplicationRecord
  include UserOath
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_one :cart, dependent: :destroy

  has_many :authorizations

  validates :email, presence: true
  validates :password, presence: true
end
    

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  layout false

  def destroy
    current_cart.destroy
    render :show
  end
  
  
end
  

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :set_page_options

  def index
    @brands = Brand.limit(3)
    @hits   = Product.limit(8)
  end
  
  def set_page_options
    @page_title       = 'Watches Shop'
    @page_description = 'Watches'
    @page_keywords    = 'Man Woman Kids'
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_page_options

  def index
    @products = Product.ransack(title_cont: params[:q]).result(distinct: true)
    
    respond_to do |format|
    format.html {}
    format.json {
      @products = @products.limit(5)
    }
    end
  end

  def set_page_options
    set_meta_tags title: 'Search'
    add_breadcrumb "Home", root_path, title: "Home"
  end
  
  def search_params
    params.permit( :query )
  end

  def text_search
    search_text = ["%" + search_params[:query] + "%"].join
    Product.where('title ILIKE ?', search_text)
  end  

   
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def products
    @products ||= cart_items.joins(:product).all
  end  
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/include/main/_bottom_header.html.erb
<div class="container">
  <div class="header">
    <div class="col-md-9 header-left">
      <div class="top-nav">
        <ul class="memenu skyblue">
          <li class="active"><%= link_to "Home", root_path, data: {turbolinks: false} %></li>
          <% Category.roots.each do |category| %>
            <% cache category do %>
              <li class="grid">
              <%= link_to category.title, "/category/#{category.id}", data: {turbolinks: false}%>
                <% if category.children.present? %>
                  <div class="mepanel">
                    <div class="row">
                      <div class="col1 me-one">
                        <%= render 'include/menu/menu', category: category, cached: true %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="col-md-3 header-right">
      <div class="search-bar">
        <!--<form action="/search" method="get" autocomplete="off">
          <input  id="categories-basic" name="q" type="text" placeholder="Search..." data-behavior="autocomlete">   
          <input type="submit" value="">         
        </form>-->
        <%= form_with url: search_index_path, local: true, method: :get, html: { autocomplete: "off", class: "form-inline my-2 my-lg-0" } do |form| %>
          <%= form.text_field :q, placeholder: "Search", data: { behavior: "autocomplete"}, class: "form-control mr-sm-2"%>
          <%= form.button "Search", class: "btn btn-outline-dark my-2 my-sm-0" %>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/include/main/_footer.html.erb
<div class="information">
  <div class="container">
    <div class="infor-top">
      <div class="col-md-3 infor-left">
        <h3>Follow Us</h3>
        <ul>
          <li><a href="https://facebook.com"><span class="fb"><h6>Facebook</h6></span></a></li>
          <li><a href="#"><span class="twit"><h6>Twitter</h6></span></a></li>
          <li><a href="#"><span class="google"><h6>Google+</h6></span></a></li>
        </ul>
      </div>
      <div class="col-md-3 infor-left">
        <h3>Information</h3>
        <ul>
          <li><a href="#"><p>Specials</p></a></li>
          <li><a href="#"><p>New Products</p></a></li>
          <li><a href="#"><p>Our Stores</p></a></li>
          <li><a href="contact.html"><p>Contact Us</p></a></li>
          <li><a href="#"><p>Top Sellers</p></a></li>
        </ul>
      </div>   
      <div class="col-md-3 infor-left">
        <h3>My Account</h3>
        <ul>
          <li><a href="account.html"><p>My Account</p></a></li>
          <li><a href="#"><p>My Credit slips</p></a></li>
          <li><a href="#"><p>My Merchandise returns</p></a></li>
          <li><a href="#"><p>My Personal info</p></a></li>
          <li><a href="#"><p>My Addresses</p></a></li>
        </ul>
      </div> 
      <div class="col-md-3 infor-left">
        <h3>Store Information</h3>
        <h4>The company name,
        <span>Lorem ipsum dolor sit.</span>
        Glasglow Dr 40 Fe 72.</h4>
        <h5>+38-050-815-42-17</h5>
        <p><a href="mailto:karamalesa@gmail.com">karamalesa@gmail.com</a></p>
      </div> 
      <div class="clearfix"></div>
    </div>  
  </div>  
</div>  
<!--information-end-->
<!--footer-starts-->
<div class="footer">
  <div class="container">
    <div class="footer-top">
      <div class="col-md-6 footer-left">
        <form>
          <input type="text" value="Enter Your Email"
            onfocus="this.value = '';"
            onblur="if (this.value = '';) {this.value = 'Enter Your Email';}">
          <input type="submit" value="Subscribe">  
        </form>
      </div>
      <div class="col-md-6 footer-right">
        <p>© 2020 Luxery Watches. All Rights Reserved</p>
      </div>  
      <div class="clearfix"></div>
    </div>
  </div>
</div>  

<!--Modal-->

<div class="modal fade" id="cart" tadindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Корзина</h4>
        <button type="button" class="close" data-dismiss="modal"  aria-label="close">&times;<span aria-hidden="true"></span></button>       
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default-outline" data-dismiss="modal">Продолжить покупки</button>
        <a href="cart/index" type="button" class="btn btn-primary">Оформить заказ</a>
        <button type="button" class="btn btn-danger" onclick="clearCart(); return false;">Очистить корзину</button>
      </div>
    </div>
  </div>
</div>

app/views/include/main/_notifications.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/include/main/_top_header.html.erb
<div class="top-header">
  <div class="container">
    <div class="top-header-main">
      <div class="col-md-6 top-header-left">
        <div class="drop">
          <div class="box">
            <select tabindex="4" class="dropdown" >
              <option value="" class="label">Dollar:</option>
              <option value="1">Dollar</option>
              <option value="2">Euro</option>
            </select>
          </div>
          <div class="box1">
            <select tabindex="4" class="dropdown">
              <option value="" class="label">English:</option>
              <option value="1">English</option>
              <option value="2">French</option>
              <option value="3">German</option>
            </select>
          </div>
          <div class="btn-group">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span>
                <% if user_signed_in? %>
                  Log out
                <% else %>
                  Log in 
                <% end %>   
              </span>
            </a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <% if current_user.try(:admin?) %>
                  <li>
                    <%= link_to "administrator", "#", style: "color: red" %>
                  </li>
                  <li>
                    <%= link_to "API", '/oauth/applications', style: "color: blue" %> 
                  </li>
                <% end %>
                <li>
                  <a href="#">
                    Добро пожаловать, <%= current_user.email %>
                  </a>
                </li>
                <li>
                  <%= link_to "Выход", destroy_user_session_path, method: :delete %>
                </li>
                <li>
                  <%= link_to "Редактирование", edit_user_registration_path, data: {turbolinks: false} %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Вход", new_user_session_path, data: {turbolinks: false} %>
                </li>
                <li>
                  <%= link_to "Регистрация", new_user_registration_path, data: {turbolinks: false} %>
                </li>  
              <% end %>
            </ul>
          </div>
          
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="">
        <div class="cart box_1">
          <a href="/cart" onclick="getCart(); return false;", data-turbolinks="false">
            <div class="total">
              <%= image_pack_tag('media/styles/images/cart-1.png', alt: "") %>
              <% if cart_items.any? %>
                <span class="simpleCart_total">
                  <%= format("%.2f", cart_total) %> $
                </span>
              <% else %>
                <span class="simpleCart_total">Empty Cart</span>  
              <% end %>
            </div>
          </a>
          <div class="clearfix"></div>
        </div>
      </div> 
      <div class="clearfix"></div>
    </div>
  </div>
</div>         

app/views/main/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_pack_tag'media/styles/images/bnr-1.jpg' %>
    </div>
    
  
    <div class="carousel-item">
      <%= image_pack_tag'media/styles/images/bnr-2.jpg' %>
    </div>
    
    
    <div class="carousel-item">
      <%= image_pack_tag'media/styles/images/bnr-3.jpg' %>
    </div>
    
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a> 
</div>
<div class="clearfix"></div>
<!--slick-slider main.js
<div class="slick-slider">
  <div><%= image_pack_tag'media/styles/images/bnr-1.jpg' %></div>
  <div><%= image_pack_tag'media/styles/images/bnr-2.jpg' %></div>
  <div><%= image_pack_tag'media/styles/images/bnr-3.jpg' %></div>
</div>
slick-slider main.js-end-->

<% if @brands.nil? %>
  <h2>no brands</h2>
<% else %>
  <!--About-Starts-->
  <div class="about">
    <div class="container">
      <div class="about-top grid-1">
        <% @brands.each do |i| %>
          <div class="col-md-4 about-left">
            <figure class="effect-bubba"> 
              <%= image_pack_tag 'media/styles/images/'+i.img, class: "img-responsive"%>
              <figcaption>
                <h2><%= i.title %></h2>
                <p><%= i.description %></p>
              </figcaption>
            </figure>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div> 
    </div>
  </div>
  <!--About-Ends-->
<% end %>

<% if @hits.nil? %>
  <h2>no hits</h2>
<% else %>
  <!--product-starts-->
  <div class="product">
    <div class="container">
      <div class="product-top">
        <div class="product-one">
          <% @hits.hit.each do |hit| %>
            <div class="product-left col-md-3">
              <div class="product-main">
                
                <a href="product/<%=hit.id%>" class="mask" data-turbolinks="false">
                
                  <%= image_pack_tag 'media/styles/images/'+hit.img, alt: "", class: "img-responsive zoom-img" %>
                
                </a>
              
                <div class="product-bottom">
                  <h3><a href="product/<%=hit.id%>" data-turbolinks="false"><%=hit.title%></a></h3>
                  <p>Explore Now</p>
                  <h4>
                    <%= link_to '/cart/cart_items', class: 'add-to-cart-link', data: { id: hit.id } do %>
                      <i></i>
                    <% end %>
                    <span class="item_price">$ <%= hit.price %></span>
                    <% if hit.old_price%>
                      <small><del>$ <%= hit.old_price %></del></small>
                    <% end %>
                  </h4>
                </div>
                <div class="srch">
                  <span>
                    - 50 %
                  </span>
                </div>
              </div>
            </div>
          <% end %>                          
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
<% end %>  
<!--product-end-->
<input type="hidden" value="<%= !current_user.nil? ? 88 : 99 %>" id="cart_access" />          

app/views/search/index.html.erb
<!--start-breadcrumb-->
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <li><a href="/"><%= render_breadcrumbs %></a></li>
        <li>Поиск по запросу</li>
      </ol>
    </div>
  </div>
</div>
<!--end-breadcrumb-->
<!--prdt-starts-->
<div class="prdt">
  <div class="container">
    <div class="prdt-top">
      <div class="col-md-9 prdt-left">
        <% if @products %>
          <div class="product-one">
            <% @products.each do |prod| %>
              <div class="col-md-4 product-left p-left">
                <div class="product-main simpleCart_shelfItem">
                <a href="/product/<%=prod.id%>" class="mask"> 
                    <img class="img-responsive zoom-img" src="<%= asset_path prod.img %>" alt="">
                  </a>
                 
                  <div class="product-bottom">
                    <h3><%=prod.title %></h3>
                    <p>Explore Now</p>
                    <h4>$ <%= prod.price %></h4>
                    <del>$ <%= prod.old_price %></del>
                  </div>
                  <div class="srch srch1">
                    <span>-50%</span>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="clearfix"></div>
          </div>
        <% else %>
          <h3>Nothing to show</h3>
        <% end %>
      </div>
      <div class="col-md-3 prdt-right">
        <div class="w_sidebar">
          <section class="sky-form">
            <h4>Categories</h4>
            <div class="row1 scroll-pane">
              <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>All_Accessories</label>
              </div>
              <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Woman Watches</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Kids Watches</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Men Watches</label>
              </div>
            </div>
          </section>
          <section class="sky-form">
            <h4>Brand</h4>
            <div class="row1 row2 scroll-pane">
              <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>kurtas</label>
              </div>
              <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Sonata</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Titan</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Casio</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Omax</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Fastrack</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Sports</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Fossil</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Maxima</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Yepme</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Citizen</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Diesel</label>
              </div>
            </div>
      </section>
      <section class="sky-form">
        <h4>Color</h4>
        <ul class=w_nav2>
          <li><a href="#" class="color1"></a></li>
          <li><a href="#" class="color2"></a></li>
          <li><a href="#" class="color3"></a></li>
          <li><a href="#" class="color4"></a></li>
          <li><a href="#" class="color5"></a></li>
          <li><a href="#" class="color6"></a></li>
          <li><a href="#" class="color7"></a></li>
          <li><a href="#" class="color8"></a></li>
          <li><a href="#" class="color9"></a></li>
          <li><a href="#" class="color10"></a></li>
          <li><a href="#" class="color11"></a></li>
          <li><a href="#" class="color12"></a></li>
          <li><a href="#" class="color13"></a></li>
          <li><a href="#" class="color14"></a></li>
          <li><a href="#" class="color15"></a></li>
          <li><a href="#" class="color16"></a></li>
          <li><a href="#" class="color17"></a></li>
          <li><a href="#" class="color18"></a></li>
          <li><a href="#" class="color19"></a></li>
          <li><a href="#" class="color20"></a></li>
          <li><a href="#" class="color21"></a></li>
        </ul>
      </section>
      <section class="sky-form">
        <h4>discount</h4>
        <div class="row1 row2 scroll-pane">
          <div class="col col-4">
            <label class="radio"><input type="radio" name="radio" checked=""><i></i>60 % and above</label>
            <label class="radio"><input type="radio" name="radio"><i></i>50 % and above</label>
            <label class="radio"><input type="radio" name="radio"><i></i>40 % and above</label>
          </div>
          <div class="col col-4">
            <label class="radio"><input type="radio" name="radio"><i></i>30 % and above</label>
            <label class="radio"><input type="radio" name="radio"><i></i>20 % and above</label>
            <label class="radio"><input type="radio" name="radio"><i></i>10 % and above</label>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="clearfix"></div>
  </div>
  </div>
</div>
<!--prdt-end-->